name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

#    - name: configure
#      run: ./configure
    - name Install nasm:
      run: sudo apt install nasm

    - name: Install bochs
      run: |
      	   sudo apt-get install build-essential \
	   && sudo apt-getinstall xorg-dev \
	   && sudo apt-get install libgtk2.0-dev \
	   && sudo apt-get install vgabios bximage \
	   && sudo apt-get install git \
	   && git clone https://github.com/LYT0628/bochs-2.4.5.git \
	   && cd bochs-2.4.5 \
	   && ./configure \
	   && make && make install 
	
    - name: compile
      run: make
 
    - name: Run in Bochs
      cd .. \
      make bochs \
      q
    # - name: Run distcheck
    #   run: make distcheck
