name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

#    - name: configure
#      run: ./configure

    - name: Install dependencies
      run: sudo apt install nasm 

    - name: compile and build
      run: make 

    # - name: Run distcheck
    #   run: make distcheck
